name: Build&Test

on: [push]

jobs:
  ubuntu:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Conan
        run: |
          pip install wheel setuptools
          pip install conan --upgrade
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.6
        with:
            cmake-version: '3.21.x'
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Build c++ project
        uses: nicledomaS/cmake_build_action@v1.3
        with:
          run_tests: ON
          unit_test_build: -Dtest=ON
          cmake_args: -DCMAKE_BUILD_TYPE=Release
      - name: echo
        run: |
          pwd
          ls
      - name: Lint
        run: cppcheck --project=compile_commands.json -ifoo
